/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fidelis.interfaces;

import javax.swing.JOptionPane;

import com.fidelis.controllers.Controlador_Cadastro_Catequista;
import com.fidelis.controllers.Controlador_Cadastro_Catequizando;
import com.fidelis.persistence.Bd;

public class Fidelis_App extends javax.swing.JFrame {

 
    public Fidelis_App() {
        Bd.connect();
        initComponents();
        Bd.createTables();
    }

    private void informaServicoIndisponivel(){
        JOptionPane.showMessageDialog(this, "Serviço Indisponível, Aguarde A Implementação, Obrigado","Informação", JOptionPane.INFORMATION_MESSAGE); 
    }

    private void informaErro(){
        JOptionPane.showMessageDialog(this, "Algo de Errado aconteceu, Desculpe, Tente mais tarde ou Contate o Administrador","ERRO", JOptionPane.ERROR_MESSAGE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagem_PrincipalLabel = new javax.swing.JLabel();
        FidelisMenuBar = new javax.swing.JMenuBar();
        CadastrosMenu = new javax.swing.JMenu();
        Cad_CatequistasMenuItem = new javax.swing.JMenuItem();
        Cad_CatequizandosMenuItem = new javax.swing.JMenuItem();
        FaltasMenu = new javax.swing.JMenu();
        FaltasMenuItem = new javax.swing.JMenuItem();
        RelatoriosMenu = new javax.swing.JMenu();
        RelatorioMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fidelis App - Semper Fidelis Crux");
        setName("Janela_Fidelis"); // NOI18N

        Imagem_PrincipalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jesus e os Apostolos.jpg"))); // NOI18N
        Imagem_PrincipalLabel.setMaximumSize(new java.awt.Dimension(250, 250));
        Imagem_PrincipalLabel.setMinimumSize(new java.awt.Dimension(250, 250));
        Imagem_PrincipalLabel.setPreferredSize(new java.awt.Dimension(250, 250));

        CadastrosMenu.setText("Cadastros");

        Cad_CatequistasMenuItem.setText("Cadastro Catequistas");
        Cad_CatequistasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_CatequistasMenuItemActionPerformed(evt);
            }
        });
        CadastrosMenu.add(Cad_CatequistasMenuItem);

        Cad_CatequizandosMenuItem.setText("Cadastro Catequizandos");
        Cad_CatequizandosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_CatequizandosMenuItemActionPerformed(evt);
            }
        });
        CadastrosMenu.add(Cad_CatequizandosMenuItem);

        FidelisMenuBar.add(CadastrosMenu);

        FaltasMenu.setText("Ver. Faltas");

        FaltasMenuItem.setText("Verificar Faltas");
        FaltasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaltasMenuItemActionPerformed(evt);
            }
        });
        FaltasMenu.add(FaltasMenuItem);

        FidelisMenuBar.add(FaltasMenu);

        RelatoriosMenu.setText("Relatorios");

        RelatorioMenuItem.setText("Relatorio de Faltas");
        RelatorioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioMenuItemActionPerformed(evt);
            }
        });
        RelatoriosMenu.add(RelatorioMenuItem);

        FidelisMenuBar.add(RelatoriosMenu);

        setJMenuBar(FidelisMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(Imagem_PrincipalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Imagem_PrincipalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cad_CatequistasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_CatequistasMenuItemActionPerformed
        try{new Controlador_Cadastro_Catequista();
        } catch(Exception e){
           informaErro();
           e.printStackTrace();
        }
    }//GEN-LAST:event_Cad_CatequistasMenuItemActionPerformed

    private void Cad_CatequizandosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_CatequizandosMenuItemActionPerformed
        try{new Controlador_Cadastro_Catequizando();
        } catch(Exception e){
            informaErro();
           e.printStackTrace();
        }
    }//GEN-LAST:event_Cad_CatequizandosMenuItemActionPerformed

    private void FaltasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaltasMenuItemActionPerformed
        informaServicoIndisponivel();
    }//GEN-LAST:event_FaltasMenuItemActionPerformed

    private void RelatorioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioMenuItemActionPerformed
        informaServicoIndisponivel();
    }//GEN-LAST:event_RelatorioMenuItemActionPerformed



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fidelis_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fidelis_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fidelis_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fidelis_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cad_CatequistasMenuItem;
    private javax.swing.JMenuItem Cad_CatequizandosMenuItem;
    private javax.swing.JMenu CadastrosMenu;
    private javax.swing.JMenu FaltasMenu;
    private javax.swing.JMenuItem FaltasMenuItem;
    private javax.swing.JMenuBar FidelisMenuBar;
    private javax.swing.JLabel Imagem_PrincipalLabel;
    private javax.swing.JMenuItem RelatorioMenuItem;
    private javax.swing.JMenu RelatoriosMenu;
    // End of variables declaration//GEN-END:variables
}
