/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fidelis.interfaces;

import javax.swing.JOptionPane;

import com.fidelis.controllers.Controlador_Login;

/**
 *
 * @author Guila
 */
public class JanelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form JanelaLogin
     */
    public JanelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome_LoginLabel = new javax.swing.JLabel();
        Nome_LoginTextField = new javax.swing.JTextField();
        Senha_LoginLabel = new javax.swing.JLabel();
        Senha_LoginTextField = new javax.swing.JTextField();
        LogarButton = new javax.swing.JButton();
        LimparLoginButton = new javax.swing.JButton();
        SairLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fidelis App - Semper Fidelis Crux");
        setName("Janela_Login_Fidelis");

        Nome_LoginLabel.setText("Nome do Usuário:");

        Senha_LoginLabel.setText("Digite sua Senha:");

        LogarButton.setText("Logar");
        LogarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarButtonActionPerformed(evt);
            }
        });

        LimparLoginButton.setText("Limpar");
        LimparLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparLoginButtonActionPerformed(evt);
            }
        });

        SairLoginButton.setText("Sair");
        SairLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Senha_LoginLabel)
                            .addComponent(Nome_LoginLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome_LoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Senha_LoginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addGap(93, 93, 93))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LimparLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SairLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_LoginLabel)
                    .addComponent(Nome_LoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Senha_LoginLabel)
                    .addComponent(Senha_LoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimparLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SairLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarButtonActionPerformed
        String nome = Nome_LoginTextField.getText();
        String senha = Senha_LoginTextField.getText();

        Controlador_Login controlador = new Controlador_Login();
        boolean loginBemSucedido = controlador.Logar(nome, senha);

        if(loginBemSucedido){
            JOptionPane.showMessageDialog(this, "Login Realizado com Sucesso!");
            this.dispose();

            Fidelis_App fidelis_App = new Fidelis_App();
            fidelis_App.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this,"Nome ou Senha Inválidos, tente novamente.","Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_LogarButtonActionPerformed

    private void LimparLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparLoginButtonActionPerformed
        Nome_LoginTextField.setText("");
        Senha_LoginTextField.setText("");
    }//GEN-LAST:event_LimparLoginButtonActionPerformed

    private void SairLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairLoginButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_SairLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*Lembrete: Colocar para acessar a tela principal - Fidelis.app */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparLoginButton;
    private javax.swing.JButton LogarButton;
    private javax.swing.JLabel Nome_LoginLabel;
    private javax.swing.JTextField Nome_LoginTextField;
    private javax.swing.JButton SairLoginButton;
    private javax.swing.JLabel Senha_LoginLabel;
    private javax.swing.JTextField Senha_LoginTextField;
    // End of variables declaration//GEN-END:variables
}
