/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fidelis.interfaces;

/**
 *
 * @author Guila
 */
public class JanelaVerificarFaltas extends javax.swing.JFrame {

    /**
     * Creates new form JanelaRelatorios
     */
    public JanelaVerificarFaltas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salvar_FaltasButton = new javax.swing.JButton();
        Nome_Catequista_FaltasLabel = new javax.swing.JLabel();
        Catequista_Lista_FaltasComboBox = new javax.swing.JComboBox();
        Data_FaltaLabel = new javax.swing.JLabel();
        Data_FaltasFormattedTextField = new javax.swing.JFormattedTextField();
        Consultar_FaltasButton = new javax.swing.JButton();
        Deletar_FaltasButton = new javax.swing.JButton();
        Editar_FaltasButton = new javax.swing.JButton();
        Catequizando_Lista_FaltasComboBox = new javax.swing.JComboBox();
        Catequizando_Nome_FaltasLabel = new javax.swing.JLabel();
        FaltaCheckBox = new javax.swing.JCheckBox();
        Falta_CheckLabel = new javax.swing.JLabel();
        DescriçãoTextField = new javax.swing.JTextField();
        DescriçãoLabel = new javax.swing.JLabel();
        LimparCamposFaltasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(560, 325));

        Salvar_FaltasButton.setText("Salvar");
        Salvar_FaltasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_FaltasButtonActionPerformed(evt);
            }
        });

        Nome_Catequista_FaltasLabel.setText("Nome do catequista:");

        Catequista_Lista_FaltasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Catequista_Lista_FaltasComboBoxActionPerformed(evt);
            }
        });

        Data_FaltaLabel.setText("Data:");

        Data_FaltasFormattedTextField.setToolTipText("--/--/----");

        Consultar_FaltasButton.setText("Consultar");
        Consultar_FaltasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_FaltasButtonActionPerformed(evt);
            }
        });

        Deletar_FaltasButton.setText("Deletar");
        Deletar_FaltasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deletar_FaltasButtonActionPerformed(evt);
            }
        });

        Editar_FaltasButton.setText("Editar");
        Editar_FaltasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_FaltasButtonActionPerformed(evt);
            }
        });

        Catequizando_Nome_FaltasLabel.setText("Nome do Catequizando:");

        FaltaCheckBox.setText("Sim");

        Falta_CheckLabel.setText("Faltou?");

        DescriçãoLabel.setText("Descrição:");

        LimparCamposFaltasButton.setText("Limpar");
        LimparCamposFaltasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCamposFaltasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar_FaltasButton)
                        .addGap(18, 18, 18)
                        .addComponent(Editar_FaltasButton)
                        .addGap(18, 18, 18)
                        .addComponent(Consultar_FaltasButton)
                        .addGap(18, 18, 18)
                        .addComponent(Deletar_FaltasButton)
                        .addGap(18, 18, 18)
                        .addComponent(LimparCamposFaltasButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DescriçãoLabel)
                            .addGap(18, 18, 18)
                            .addComponent(DescriçãoTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Nome_Catequista_FaltasLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(Catequista_Lista_FaltasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Catequizando_Nome_FaltasLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Catequizando_Lista_FaltasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(Data_FaltaLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(Data_FaltasFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Falta_CheckLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(FaltaCheckBox))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_Catequista_FaltasLabel)
                    .addComponent(Catequista_Lista_FaltasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data_FaltaLabel)
                    .addComponent(Data_FaltasFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Catequizando_Lista_FaltasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Catequizando_Nome_FaltasLabel)
                    .addComponent(FaltaCheckBox)
                    .addComponent(Falta_CheckLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriçãoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriçãoLabel))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar_FaltasButton)
                    .addComponent(Editar_FaltasButton)
                    .addComponent(Consultar_FaltasButton)
                    .addComponent(Deletar_FaltasButton)
                    .addComponent(LimparCamposFaltasButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Catequista_Lista_FaltasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Catequista_Lista_FaltasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Catequista_Lista_FaltasComboBoxActionPerformed

    private void Salvar_FaltasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_FaltasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salvar_FaltasButtonActionPerformed

    private void Editar_FaltasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_FaltasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Editar_FaltasButtonActionPerformed

    /* Tem que ter a visão do catequizando + nº de faltas ou 
    Separar a qtd de faltas em um textfield, e dps analisar se seria interessante
    Dar Disable ou Enable para somente quanto o usuário for editar. */
    private void Consultar_FaltasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_FaltasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultar_FaltasButtonActionPerformed

    private void Deletar_FaltasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deletar_FaltasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Deletar_FaltasButtonActionPerformed

    private void LimparCamposFaltasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCamposFaltasButtonActionPerformed
        Data_FaltasFormattedTextField.setText("");
        DescriçãoTextField.setText("");
        FaltaCheckBox.setSelected(false);
    }//GEN-LAST:event_LimparCamposFaltasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificarFaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificarFaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificarFaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificarFaltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JanelaVerificarFaltas().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Catequista_Lista_FaltasComboBox;
    private javax.swing.JComboBox Catequizando_Lista_FaltasComboBox;
    private javax.swing.JLabel Catequizando_Nome_FaltasLabel;
    private javax.swing.JButton Consultar_FaltasButton;
    private javax.swing.JLabel Data_FaltaLabel;
    private javax.swing.JFormattedTextField Data_FaltasFormattedTextField;
    private javax.swing.JButton Deletar_FaltasButton;
    private javax.swing.JLabel DescriçãoLabel;
    private javax.swing.JTextField DescriçãoTextField;
    private javax.swing.JButton Editar_FaltasButton;
    private javax.swing.JCheckBox FaltaCheckBox;
    private javax.swing.JLabel Falta_CheckLabel;
    private javax.swing.JButton LimparCamposFaltasButton;
    private javax.swing.JLabel Nome_Catequista_FaltasLabel;
    private javax.swing.JButton Salvar_FaltasButton;
    // End of variables declaration//GEN-END:variables
}
