/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fidelis.interfaces;

/**
 *
 * @author Guila
 */
public class JanelaDeRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form JanelaVerificaFaltas
     */
    public JanelaDeRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome_Cat_RelatorioLabel = new javax.swing.JLabel();
        Catequista_RelatorioComboBox = new javax.swing.JComboBox<>();
        Data_Falta_RelatorioLabel = new javax.swing.JLabel();
        Data_Faltas_RelatorioFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        RelatorioTextArea = new javax.swing.JTextArea();
        ImprimirButton = new javax.swing.JButton();
        Consultar_RelatorioButton = new javax.swing.JButton();
        Relatorio_FaltasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nome_Cat_RelatorioLabel.setText("Nome do catequista:");

        Data_Falta_RelatorioLabel.setText("Data das Faltas:");

        Data_Faltas_RelatorioFormattedTextField.setToolTipText("--/--/----");

        RelatorioTextArea.setColumns(20);
        RelatorioTextArea.setRows(5);
        jScrollPane1.setViewportView(RelatorioTextArea);

        ImprimirButton.setText("Imprimir");
        ImprimirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirButtonActionPerformed(evt);
            }
        });

        Consultar_RelatorioButton.setText("Consultar Relatorio");
        Consultar_RelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_RelatorioButtonActionPerformed(evt);
            }
        });

        Relatorio_FaltasLabel.setText("Relatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nome_Cat_RelatorioLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Catequista_RelatorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Data_Falta_RelatorioLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Data_Faltas_RelatorioFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Relatorio_FaltasLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(ImprimirButton)
                        .addGap(141, 141, 141)
                        .addComponent(Consultar_RelatorioButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_Cat_RelatorioLabel)
                    .addComponent(Catequista_RelatorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data_Falta_RelatorioLabel)
                    .addComponent(Data_Faltas_RelatorioFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Relatorio_FaltasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimirButton)
                    .addComponent(Consultar_RelatorioButton))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImprimirButtonActionPerformed

    private void Consultar_RelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_RelatorioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultar_RelatorioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaDeRelatorios().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> Catequista_RelatorioComboBox;
    private javax.swing.JButton Consultar_RelatorioButton;
    private javax.swing.JLabel Data_Falta_RelatorioLabel;
    private javax.swing.JFormattedTextField Data_Faltas_RelatorioFormattedTextField;
    private javax.swing.JButton ImprimirButton;
    private javax.swing.JLabel Nome_Cat_RelatorioLabel;
    private javax.swing.JTextArea RelatorioTextArea;
    private javax.swing.JLabel Relatorio_FaltasLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
