/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fidelis.interfaces;

import javax.swing.JOptionPane;
import com.fidelis.entities.Catequizando;
import javax.swing.DefaultComboBoxModel;
import com.fidelis.controllers.Controlador_Cadastro_Catequizando;


public class JanelaCadastroCatequizando extends javax.swing.JFrame {

    Controlador_Cadastro_Catequizando controlador_Catequizando;
    Catequizando[] catequizandos_cadastrados;

    public JanelaCadastroCatequizando(Controlador_Cadastro_Catequizando controlador_Catequizando) {
        this.controlador_Catequizando = controlador_Catequizando;
        catequizandos_cadastrados = Catequizando.getVisao_Catequizandos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({ "unchecked", "rawtypes" })
    private void initComponents() {

        Nome_CatequizandoTextField = new javax.swing.JTextField();
        Nome_CatequizandoLabel = new javax.swing.JLabel();
        Idade_CatequizandoTextField = new javax.swing.JTextField();
        Idade_CatequizandoLabel = new javax.swing.JLabel();
        data_inicio_catFormattedTextField = new javax.swing.JFormattedTextField();
        data_inicio_catLabel = new javax.swing.JLabel();
        Qtd_Faltas_CatequizandoTextField = new javax.swing.JTextField();
        Qtd_FaltasLabel = new javax.swing.JLabel();
        Inserir_CatequizandoButton = new javax.swing.JButton();
        Editar_CatequizandoButton = new javax.swing.JButton();
        Remover_CatequizandoButton = new javax.swing.JButton();
        Consultar_CatequizandoButton = new javax.swing.JButton();
        CatequizandoCadastradoLabel = new javax.swing.JLabel();
        catequizando_CadastradoComboBox = new javax.swing.JComboBox<>();
        LimparCatequizandoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Catequizando");

        Nome_CatequizandoLabel.setText("Nome Catequizando:");

        Idade_CatequizandoLabel.setText("Idade:");

        data_inicio_catFormattedTextField.setToolTipText("00/00/0000");

        data_inicio_catLabel.setText("Data de Inicio da Catequese:");

        Qtd_Faltas_CatequizandoTextField.setToolTipText("000");

        Qtd_FaltasLabel.setText("Quantidade de Faltas:");

        Inserir_CatequizandoButton.setText("Inserir");
        Inserir_CatequizandoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_CatequizandoButtonActionPerformed(evt);
            }
        });

        Editar_CatequizandoButton.setText("Editar");
        Editar_CatequizandoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_CatequizandoButtonActionPerformed(evt);
            }
        });

        Remover_CatequizandoButton.setText("Remover");
        Remover_CatequizandoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_CatequizandoButtonActionPerformed(evt);
            }
        });

        Consultar_CatequizandoButton.setText("Consultar");
        Consultar_CatequizandoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_CatequizandoButtonActionPerformed(evt);
            }
        });

        CatequizandoCadastradoLabel.setText("Catequizando Cadastrado:");

        catequizando_CadastradoComboBox.setModel(new DefaultComboBoxModel(catequizandos_cadastrados));

        LimparCatequizandoButton.setText("Limpar");
        LimparCatequizandoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos_CatequizandoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CatequizandoCadastradoLabel)
                        .addGap(38, 38, 38)
                        .addComponent(catequizando_CadastradoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Qtd_FaltasLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Qtd_Faltas_CatequizandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Idade_CatequizandoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Idade_CatequizandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nome_CatequizandoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nome_CatequizandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(data_inicio_catLabel)
                                .addGap(18, 18, 18)
                                .addComponent(data_inicio_catFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Inserir_CatequizandoButton)
                                .addGap(18, 18, 18)
                                .addComponent(Editar_CatequizandoButton)
                                .addGap(18, 18, 18)
                                .addComponent(Consultar_CatequizandoButton)
                                .addGap(18, 18, 18)
                                .addComponent(Remover_CatequizandoButton)
                                .addGap(18, 18, 18)
                                .addComponent(LimparCatequizandoButton)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatequizandoCadastradoLabel)
                    .addComponent(catequizando_CadastradoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_CatequizandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome_CatequizandoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idade_CatequizandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Idade_CatequizandoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_inicio_catFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_inicio_catLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qtd_FaltasLabel)
                    .addComponent(Qtd_Faltas_CatequizandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inserir_CatequizandoButton)
                    .addComponent(Editar_CatequizandoButton)
                    .addComponent(Remover_CatequizandoButton)
                    .addComponent(Consultar_CatequizandoButton)
                    .addComponent(LimparCatequizandoButton))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inserir_CatequizandoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_CatequizandoButtonActionPerformed
        Catequizando catequizando = obterCatequizandosInformados();
        String msg_erro = null;
        if(catequizando != null)
           msg_erro = controlador_Catequizando.inserirCatequizandoCadastrado(catequizando);
         else msg_erro = "Algum Atributo do Catequizando não foi informado";
        if(msg_erro == null){
           Catequizando visao = catequizando.getVisao();
           catequizando_CadastradoComboBox.addItem(visao);
           catequizando_CadastradoComboBox.updateUI();
           catequizando_CadastradoComboBox.setSelectedItem(visao);
         } else JOptionPane.showMessageDialog(this, msg_erro ,"ERRO",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Inserir_CatequizandoButtonActionPerformed

    private void Editar_CatequizandoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_CatequizandoButtonActionPerformed
        Catequizando catequizando = obterCatequizandosInformados();
        String msg_erro = null;
        if(catequizando != null)
            msg_erro = controlador_Catequizando.editarCatequizandoCadastrado(catequizando);
        else msg_erro = "Algum atributo do Catequizando não foi Informado";
        if(msg_erro == null){
            Catequizando visao = getVisaoCatequizandosCadastrados(catequizando.getId(), catequizando.getNome_catequizando());
            if(visao != null && visao.getId() > 0){
                visao.setNome_catequizando(catequizando.getNome_catequizando());
                catequizando_CadastradoComboBox.updateUI();
                catequizando_CadastradoComboBox.setSelectedItem(visao);
            }
        } else JOptionPane.showMessageDialog(this, msg_erro ,"ERRO",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Editar_CatequizandoButtonActionPerformed

    private void Consultar_CatequizandoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_CatequizandoButtonActionPerformed
        Catequizando visao = (Catequizando) catequizando_CadastradoComboBox.getSelectedItem();
        Catequizando catequizando = null;
        String msg_erro = null;
        if(visao != null && visao.getId() > 0){
            catequizando = Catequizando.consultarCatequizandos(visao.getId());
            if(catequizando == null){
                msg_erro = "Catequizando não Cadastrado";
            }
        } else msg_erro = "Nenhum Catequizando foi Selecionado";
        if(msg_erro == null && catequizando != null){
            Nome_CatequizandoTextField.setText(catequizando.getNome_catequizando());
            Idade_CatequizandoTextField.setText(catequizando.getIdade());
            data_inicio_catFormattedTextField.setText(catequizando.getData_inicio_cat());
            Qtd_Faltas_CatequizandoTextField.setText(catequizando.getQtd_faltas());
        } else JOptionPane.showMessageDialog(this, msg_erro ,"ERRO",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Consultar_CatequizandoButtonActionPerformed

    private void Remover_CatequizandoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_CatequizandoButtonActionPerformed
        Catequizando visao = (Catequizando) catequizando_CadastradoComboBox.getSelectedItem();
        String msg_erro = null;
        if(visao != null)
          msg_erro = controlador_Catequizando.removerCatequizandoCadastrado(visao.getId());
        else msg_erro = "Nenhum Catequizando foi Selecionado";
        if(msg_erro == null){
           catequizando_CadastradoComboBox.removeItem(visao);
           if(catequizandos_cadastrados.length >= 1){
                catequizando_CadastradoComboBox.setSelectedIndex(0);
                catequizando_CadastradoComboBox.updateUI();
           } else catequizando_CadastradoComboBox.setSelectedIndex(-1);
        } else{
           JOptionPane.showMessageDialog(this, msg_erro ,"ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Remover_CatequizandoButtonActionPerformed

    private void limparCampos_CatequizandoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos_CatequizandoButtonActionPerformed
        Nome_CatequizandoTextField.setText("");
        data_inicio_catFormattedTextField.setText("");
        Idade_CatequizandoTextField.setText("");
        Qtd_Faltas_CatequizandoTextField.setText("");
    }//GEN-LAST:event_limparCampos_CatequizandoButtonActionPerformed

    private Catequizando getVisaoCatequizandosCadastrados(int id_catequizando, String nome_catequizando){
        for(Catequizando visao : catequizandos_cadastrados){
           if(nome_catequizando.equals(visao.getNome_catequizando()) && visao.getId() == id_catequizando){
           } else {
           return visao;
           }
        }
        return null;
   }

   public Catequizando obterCatequizandosInformados(){
    String nome_catequizando = Nome_CatequizandoTextField.getText();
    if(nome_catequizando.isEmpty()) return null;
    String data_inicio_cat = data_inicio_catFormattedTextField.getText();
    if(data_inicio_cat.isEmpty()) return null;
    String idade = Idade_CatequizandoTextField.getText();
    if(idade.isEmpty()) return null;
    String qtd_faltas = Qtd_Faltas_CatequizandoTextField.getText();
    if(qtd_faltas.isEmpty()) return null;
    Boolean faltas = false;
    return new Catequizando(nome_catequizando, idade, data_inicio_cat, qtd_faltas, faltas);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCatequizando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCatequizando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCatequizando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCatequizando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() { }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CatequizandoCadastradoLabel;
    private javax.swing.JButton Consultar_CatequizandoButton;
    private javax.swing.JButton Editar_CatequizandoButton;
    private javax.swing.JLabel Idade_CatequizandoLabel;
    private javax.swing.JTextField Idade_CatequizandoTextField;
    private javax.swing.JButton Inserir_CatequizandoButton;
    private javax.swing.JButton LimparCatequizandoButton;
    private javax.swing.JLabel Nome_CatequizandoLabel;
    private javax.swing.JTextField Nome_CatequizandoTextField;
    private javax.swing.JLabel Qtd_FaltasLabel;
    private javax.swing.JTextField Qtd_Faltas_CatequizandoTextField;
    private javax.swing.JButton Remover_CatequizandoButton;
    private javax.swing.JComboBox<Object> catequizando_CadastradoComboBox;
    private javax.swing.JFormattedTextField data_inicio_catFormattedTextField;
    private javax.swing.JLabel data_inicio_catLabel;
    // End of variables declaration//GEN-END:variables
}
